//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.People.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("School.People.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressIdsTable.
        /// </summary>
        internal static string AddressIdsTableName {
            get {
                return ResourceManager.GetString("AddressIdsTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgencyMemberDetailsTable.
        /// </summary>
        internal static string AgencyMemberDetailsTableName {
            get {
                return ResourceManager.GetString("AgencyMemberDetailsTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CharacterReferencesIdsTable.
        /// </summary>
        internal static string CharacterReferencesIdsTableName {
            get {
                return ResourceManager.GetString("CharacterReferencesIdsTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CitizenshipsTable.
        /// </summary>
        internal static string CitizenshipTableName {
            get {
                return ResourceManager.GetString("CitizenshipTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CivicWorksTable.
        /// </summary>
        internal static string CivicWorkTableName {
            get {
                return ResourceManager.GetString("CivicWorkTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactDetailsTable.
        /// </summary>
        internal static string ContactDetailsTableName {
            get {
                return ResourceManager.GetString("ContactDetailsTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateOfBirthsTable.
        /// </summary>
        internal static string DateOfBirthTableName {
            get {
                return ResourceManager.GetString("DateOfBirthTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EducationsTable.
        /// </summary>
        internal static string EducationTableName {
            get {
                return ResourceManager.GetString("EducationTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EligibilitiesTable.
        /// </summary>
        internal static string EligibilityTableName {
            get {
                return ResourceManager.GetString("EligibilityTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FamilyIdsTable.
        /// </summary>
        internal static string FamilyIdsTableName {
            get {
                return ResourceManager.GetString("FamilyIdsTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FaqsTable.
        /// </summary>
        internal static string FaqsTableName {
            get {
                return ResourceManager.GetString("FaqsTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImagesTable.
        /// </summary>
        internal static string ImageTableName {
            get {
                return ResourceManager.GetString("ImageTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OtherInformationsTable.
        /// </summary>
        internal static string OtherInformationTableName {
            get {
                return ResourceManager.GetString("OtherInformationTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonDetailsTable.
        /// </summary>
        internal static string PersonDetailsTableName {
            get {
                return ResourceManager.GetString("PersonDetailsTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PeopleTable.
        /// </summary>
        internal static string PersonTableName {
            get {
                return ResourceManager.GetString("PersonTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrainingsTable.
        /// </summary>
        internal static string TrainingTableName {
            get {
                return ResourceManager.GetString("TrainingTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VerificationDetailsTable.
        /// </summary>
        internal static string VerificationDetailsTableName {
            get {
                return ResourceManager.GetString("VerificationDetailsTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorksTable.
        /// </summary>
        internal static string WorkTableName {
            get {
                return ResourceManager.GetString("WorkTableName", resourceCulture);
            }
        }
    }
}
